import { Analytics } from '@vercel/analytics/react';
import Nav from './auth/Nav'
import './globals.css'
import { Inter } from 'next/font/google'
import QueryWrapper from './auth/QueryWrapper'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`mx-4 md:mx-48 xl:mx-96 ${inter.className} font-sans bg-gray-200`}>
        <QueryWrapper>
          <Nav />
          {children}
        </QueryWrapper>
        <Analytics />
      </body>
    </html>
  )
}
